name: tests
on:
  pull_request:
jobs:
  cabal:
    name: ${{ matrix.os }} / ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["8.6", "8.8", "8.10"]
        # Newer versions of GHC are broken on Windows:
        # https://gitlab.haskell.org/ghc/ghc/-/issues/17926
        exclude:
          - os: windows-latest
            ghc: "8.8"
          - os: windows-latest
            ghc: "8.10"
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure and Freeze for Cache
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct -fmaintainer
          cabal freeze

      - name: Cache ~/.cabal/store
        uses: actions/cache@v1
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: cabal build all '--build-log=logs/$pkgid'

      - name: Test
        run: cabal test all

      - name: Upload Build Logs on Failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs-${{ matrix.os }}-ghc${{ matrix.ghc }}
          path: logs/
